version: '3'

services:
  database:
    image: mongo:latest
    container_name: mongodb-container-for-restaurants
    volumes:
      - mongo-volumes-for-restaurants:/data/db
    ports:
      - 27019:27017

  server:
    build: .
    image: server-image-for-restaurants
    container_name: server-container-for-restaurants
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - database

volumes:
  mongo-volumes-for-restaurants:
