version: '3'

services:
  database:
    image: mongo:latest
    container_name: my-mongo-container
    volumes:
      - mongo:/data/db
    ports:
      - 27018:27017

  app:
    build: .
    container_name: my-node-app
    ports:
      - 3000:3000
    depends_on:
      - database

volumes:
  mongo:
